### PR TITLE
New docs

### PR DESCRIPTION
**Pull request by bchangsorensen**
Practicing writing doc blocks

### CODE REVIEW

**Review by elenarunsbk — APPROVED** [review]
I think this looks good! Really neat with a separate doc file!
I was also trying to clone your repo and do dbt docs generate and dbt docs serve to look at what it looks like in the browser but somehow I wasn't seeing these latest changes there. Wonder if I'm missing some git step to see the latest changes

**Comment by mikekaminsky** [comment]
> I was also trying to clone your repo and do dbt docs generate and dbt docs serve to look at what it looks like in the browser but somehow I wasn't seeing these latest changes there. Wonder if I'm missing some git step to see the latest changes

@ElenaRusAthletx did you actually check out this branch? The steps are:

1. Clone the repo
2. Check out the feature branch: `git checkout new-docs` in this case
3. `git pull` (maybe?)
4. Then run docs serve.

**Comment by bchangsorensen** [comment]
@mikekaminsky so `git clone` pulls every branch by default? Good to know! I was just Googling how to clone a specific branch in case that was the issue.

**Comment by elenarunsbk** [comment]
@mikekaminsky ok dumb mistake again on my part! I did `git checkout new_docs` instead of `git checkout new-docs`

**Pull request merged**
